# Arquivo de configuração global

# Definições de variáveis
LOG_FILE="infra_it.log"
SENHA_PADRAO="Insira a senha aqui"

# Validação de segurança da senha
if [ "${#SENHA_PADRAO}" -lt 8 ]; then
    echo "❌ ERRO CRÍTICO NO CONFIG.CONF:"
    echo "   A variável SENHA_PADRAO deve possuir no mínimo 8 caracteres para segurança."
    exit 1
fi